function h = mapfield(f,grd,ldir)

% MAPFIELD maps a field generated by the GSHS function.
%
% h = mapfield(f,grd,ldir)
% 
% INPUT
% f     -   Field generated by GSHS function.
% grd   -   optional string argument, defining the grid:
%             1) 'pole' or 'mesh': equi-angular (N+1)*2N, including poles
%                and Greenwich meridian. 			- def: 'pole'
%             2) 'block' or 'cell': equi-angular block midpoints. N*2N
%             3) 'neumann' or 'gauss': Gauss-grid (N+1)*2N [char]
% ldir  -   '1' indicates longitude is arranged 0 to 360 and '0' indicates
%           -180 to 180 arrangement.
%
% OUTPUT
% Generates a map of the field
% h         -   A structure containing the handles for the following:
% h.fig     -   Handle of the figure.
% h.img     -   Handle of the grid image
% h.axis    -   Axis handle
% h.cbar    -   Colorbar handle
%--------------------------------------------------------------------------
% USES uberall/grule
%
% NOTE: Requires mapping toolbox for plotting coastlines!!!!
%
%--------------------------------------------------------------------------

% 6 May 2011, Stuttgart. Balaji Devaraju
%--------------------------------------------------------------------------

if nargin ~= 3
    error('Insufficient input arguments')
end

% ------------------------
% Grid definition.
% ------------------------
n = size(f,1);
if strcmp(grd,'pole') || strcmp(grd,'mesh')
    dt      = 180/(n - 1);
    theta   = (0:dt:180)';
    lam     = (0:dt:360-dt);
elseif strcmp(grd,'block') || strcmp(grd,'cell')
    dt      = 180/(n - 1);
    theta   = (dt/2:dt:180)';
    lam     = (dt/2:dt:360);
elseif strcmp(grd,'neumann') || strcmp(grd,'gauss')
    dlam    = 180/(n - 1);
    gx      = grule(n);
    theta   = flipud(acos(standing(gx)))*180/pi;
    lam     = (0:dlam:360-dlam);
else
   error('What type of grid do you want?')
end

lam(lam > 180)  = lam(lam > 180) - 360;
[lam,indx]      = sort(lam);
if logical(ldir)
    f               = f(:,indx);
end

h.fig   = figure;
h.img   = imagesc(lam, 90-theta, f);
h.axis  = gca();
hold on
load coast
plot(long,lat,'k')
pbaspect([2 1 1])
axis xy
h.cbar  = colorbar;
